Criptext/Criptext-Email-React-Client

- .circleci/config.yml
- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/utils/__tests__/EmailUtils.js
- electron_app/yarn.lock
- email_login/src/components/ContinueLogin.js
- email_login/src/components/DeviceNotApproved.js
- email_login/src/components/LoginWrapper.js
- email_login/src/components/LostAllDevices.js
- email_login/src/components/LostAllDevicesWrapper.js
- email_mailbox/src/components/SettingGeneral.js
- email_mailbox/src/components/SettingGeneralWrapper.js
- email_mailbox/src/components/SettingsWrapper.js
- email_mailbox/src/components/settinggeneral.scss
- email_mailbox/src/containers/Settings.js
- email_mailbox/src/utils/TimeUtils.js
- email_mailbox/src/utils/electronInterface.js
- email_mailbox/src/utils/storage.js
- Fix '**More than 2 months ago**' last activity
- **Two-Factor Authentication**
> Two-Factor Authentication

- email_login/src/components/LoginWrapper.js
Don't wait for server to validate if username exists or not before
enabling the sign in button.
> Dont wait for server to validate username (SignIn)

- electron_app/src/models.js
- electron_app/src/utils/EmailUtils.js
- electron_app/src/utils/RegexUtils.js
- electron_app/src/utils/stringUtils.js
- electron_app/src/windows/composer.js
- electron_app/src/windows/mailbox.js
- email_composer/src/components/AutocompleteWrapper.js
- email_composer/src/components/Recipient.js
- email_composer/src/containers/Composer.js
- email_composer/src/utils/EmailUtils.js
- email_loading/src/libs/signal.js
- email_mailbox/src/containers/Settings.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/storage.js
- **Do not save invalid email addresses** on Save draft
- **Open composer** when clicking **email address on Email detail**
- Autocomplete with **app domain** if you enter a username and **tap comma or space**
- Recovery email fixes on SignIn/SignUp
- Error handling for **database methods** for SI/SU
> Fix recipients & Catch mailto & Autocomplete comma/space & Fixes

- email_mailbox/src/utils/ReactUtils.js
- email_mailbox/src/utils/storage.js
Fix app crash on searching "(" or ")"
> Fix searchbox

- email_mailbox/package.json
- email_mailbox/src/app.scss
- email_mailbox/src/components/Panel.js
- email_mailbox/src/components/PanelWrapper.js
- email_mailbox/src/components/ThreadItemWrapper.js
- email_mailbox/src/components/UserGuide.js
- email_mailbox/src/lang/en.js
- email_mailbox/src/lang/es.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/storage.js
- email_mailbox/yarn.lock
Available steps:
- Compose button
- Email Read
> User Guide

- email_mailbox/src/components/SettingGeneral.js
- email_mailbox/src/components/SettingsGeneralTheme.js
- email_mailbox/src/components/SettingsGeneralThemeWrapper.js
- email_mailbox/src/components/settinggeneral.scss
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- Settings option (select)
- Update database and Settings object
> Dark theme: Functionality

- electron_app/package.json
- electron_app/yarn.lock
- email_mailbox/src/components/ManualSyncDeviceAuthenticationPopup.js
- email_mailbox/src/components/ManualSyncPopup.js
- email_mailbox/src/components/ManualSyncProcessPopup.js
- Update API Client version
- Disable buttons after click
> Fixes Manual Sync

- electron_app/src/DBManager.js
- electron_app/src/ipc/database.js
- email_mailbox/src/actions/threads.js
- email_mailbox/src/components/DialogPopup.js
- email_mailbox/src/components/Email.js
- email_mailbox/src/components/EmailWrapper.js
- email_mailbox/src/components/HeaderThreadOptions.js
- email_mailbox/src/components/HeaderThreadOptionsWrapper.js
- email_mailbox/src/components/Threads.js
- email_mailbox/src/components/ThreadsWrapper.js
- email_mailbox/src/containers/Email.js
- email_mailbox/src/containers/Message.js
- email_mailbox/src/containers/Threads.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- Adding Popups to handle permanently deletes
> Mailbox Popups

- email_composer/src/containers/Composer.js
- email_composer/src/libs/signal.js
- email_composer/src/utils/FileUtils.js
- email_mailbox/src/components/Email.js
- email_mailbox/src/components/HeaderThreadOptions.js
- email_mailbox/src/components/MainWrapper.js
- email_mailbox/src/components/Threads.js
- Added background overlay color
- Added action to dismiss overlay in mailbox
> Popup background overlay

- electron_app/src/migrations/20190116122748_fromAndReplyTo.js
- email_mailbox/src/components/ReplyTo.js
- email_mailbox/src/components/SettingGeneral.js
- email_mailbox/src/components/SettingGeneralWrapper.js
- email_mailbox/src/components/SettingsGeneralReplyTo.js
- email_mailbox/src/components/settinggeneral.scss
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- Reply To in settings was redesigned according to the review of 18/01
> Reply Design

- electron_app/src/migrations/20190116122748_fromAndReplyTo.js
- Query Limit was not working, loading all rows sqlite would give me and retrying if there are more rows
> Migration Fix

- .gitignore
- electron_app/electron-starter.js
- electron_app/package.json
- electron_app/src/__integrations__/DbExporter.integration.js
- electron_app/src/__integrations__/__snapshots__/Email.integration.js.snap
- electron_app/src/clientManager.js
- electron_app/src/dbExporter.js
- electron_app/src/ipc/database.js
- electron_app/src/ipc/manager.js
- electron_app/src/migrations/20190111104210_dropFileKey.js
- electron_app/src/migrations/20190122173904_addColumnBoundaries.js
- electron_app/src/utils/FileUtils.js
- electron_app/src/utils/PrintUtils.js
- electron_app/src/utils/__tests__/FileUtils.js
- electron_app/src/utils/const.js
- electron_app/src/utils/dataTableUtils.js
- electron_app/src/windows/composer.js
- electron_app/yarn.lock
- email_composer/src/containers/Composer.js
- email_composer/src/utils/EmailUtils.js
- email_composer/src/utils/__mocks__/ipc.js
- email_composer/src/utils/__tests__/__snapshots__/EmailUtils.js.snap
- email_composer/src/utils/ipc.js
- email_mailbox/src/actions/emails.js
- email_mailbox/src/libs/signal.js
- email_mailbox/src/utils/EmailUtils.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- Storing email body and headers in filesystem when receiving files or in sync
- Retrieving email body from filesystem when displaying email or for sync
> Storing and Retrieving body and headers from filesystem

- electron_app/src/ipc/mailbox.js
- electron_app/src/lang/en.json
- electron_app/src/lang/es.json
- electron_app/src/utils/FileUtils.js
- electron_app/src/utils/SourceUtils.js
- electron_app/src/windows/source.html
- email_mailbox/src/components/Email.js
- email_mailbox/src/components/EmailActions.js
- email_mailbox/src/containers/Email.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/ipc.js
- Displaying source option when app has boundary
- Opening a new window with email content
> Show Email Source

- electron_app/src/ipc/database.js
- electron_app/src/ipc/manager.js
- electron_app/src/utils/FileUtils.js
- electron_app/src/utils/SourceUtils.js
- electron_app/src/windows/source-dark.html
- electron_app/src/windows/source-light.html
- email_loading/src/libs/signal.js
- email_loading/src/utils/ipc.js
- View Source has a dark mode and has its UI improved
- Deleting files when db is also cleared
> View Source Dark Mode & Delete Files with DB

- electron_app/src/ipc/manager.js
- electron_app/src/utils/FileUtils.js
- electron_app/src/utils/stringUtils.js
- email_loading/src/libs/signal.js
- email_mailbox/src/components/ProfileShortCutWrapper.js
- email_mailbox/src/libs/signal.js
- email_mailbox/src/utils/electronEventInterface.js
- Welcome Email Fix
- Removing Dir Revenant Fix
> welcome fix, remove dir fix

- email_composer/src/components/NonCriptextPopupWrapper.js
- email_login/src/components/SignUpReducers.js
- email_login/src/components/SignUpReducers.test.js
- email_login/src/lang/en.json
- email_login/src/lang/es.json
- email_login/src/utils/RegexUtils.js
- email_login/src/validators/validators.js
- email_mailbox/src/utils/EmailUtils.js
- Passphrase text is visible from start
- Signup user validation text updated
> Passphrase visible and signup error text

- electron_app/src/DBManager.js
- electron_app/src/__integrations__/Email.integration.js
- email_composer/src/components/AutocompleteWrapper.js
- email_composer/src/components/AvatarImage.js
- email_composer/src/components/suggestion.scss
- email_composer/src/utils/RegexUtils.js
- email_composer/src/utils/__tests__/RegexUtils.js
- email_composer/src/utils/__tests__/__snapshots__/RegexUtils.js.snap
- email_mailbox/src/containers/ThreadItem.js
- Suggestions now match LastName of contacts
> Suggestions

- email_composer/src/libs/signal.js
` `
Check **Test cases** on issue description
` `
> Fix guest email

- electron_app/electron-starter.js
- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/ipc/client.js
- electron_app/src/ipc/mailbox.js
- electron_app/src/ipc/utils.js
- electron_app/src/lang/en.json
- electron_app/src/lang/es.json
- electron_app/src/updater.js
- electron_app/src/windows/mailbox.js
- electron_app/src/windows/menu.js
- electron_app/src/windows/source-dark.html
- electron_app/src/windows/source-light.html
- electron_app/src/windows/tray.js
- electron_app/src/windows/windowUtils.js
- electron_app/yarn.lock
- email_mailbox/src/components/MessageWrapper.js
- email_mailbox/src/containers/Message.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/electronInterface.js
- email_mailbox/src/utils/ipc.js
- Register push token
- Handle click on notifications
- Tray icon for all platforms
> Notifications, Firebase & Tray

- email_mailbox/src/components/Email.js
- email_mailbox/src/components/ThreadItem.js
- email_mailbox/src/components/email.scss
- email_mailbox/src/components/threaditem.scss
- email_mailbox/src/containers/Email.js
- email_mailbox/src/containers/Thread.js
- email_mailbox/src/containers/ThreadItem.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/TimeUtils.js
> Empty subject, Empty content & Unsend

- email_composer/src/components/EditorWrapper.js
- email_composer/src/components/editor.scss
- email_composer/src/customPlugins/commatobr.js
- email_composer/src/utils/EmailUtils.js
- email_composer/src/utils/__tests__/__snapshots__/EmailUtils.js.snap
- Prevent remove format on paste
- Fix line-height
- Plugin Template*
- Add threadId on Forward
> Composer fixes

- electron_app/package.json
- electron_app/src/notificationManager.js
- email_mailbox/package.json
- email_mailbox/src/containers/Message.js
- Remove icon param on MacOS
- Set unread thread on click notification
> Fix notification

- email_mailbox/src/components/ChangePasswordPopup.js
Closes https://github.com/Criptext/Criptext-Email-React-Client/issues/854.
> Fix wrong placeholder in ChangePasswordPopup.js

- electron_app/src/DBManager.js
- electron_app/src/__integrations__/Contact.integration.js
- electron_app/src/__integrations__/DbExporter.integration.js
- electron_app/src/__integrations__/Email.integration.js
- electron_app/src/__integrations__/Label.integration.js
- electron_app/src/__integrations__/data/emails.json
- electron_app/src/clientManager.js
- electron_app/src/eventQueueManager.js
- electron_app/src/ipc/database.js
- electron_app/src/ipc/manager.js
- electron_app/src/models.js
- electron_app/src/utils/PrintUtils.js
- electron_app/src/utils/SourceUtils.js
- email_loading/src/libs/signal.js
- email_loading/src/utils/ipc.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
> Account Id to Queries

- electron_app/src/models.js
- email_loading/src/libs/signal.js
- Fixing Login: creating account if not exist
- Fixing Logout: retrieving accountId before updating and cleaning
> Login and Logout Fix

- electron_app/electron-starter.js
- electron_app/src/DBManager.js
- electron_app/src/__integrations__/Label.integration.js
- electron_app/src/dataTransferClient.js
- electron_app/src/dbExporter.js
- electron_app/src/ipc/dataTransfer.js
- electron_app/src/ipc/database.js
- electron_app/src/ipc/manager.js
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/components/LinkOldDeviceWrapper.js
- email_loading/src/components/SyncMailboxWrapper.js
- email_loading/src/utils/ipc.js
- email_mailbox/src/actions/emails.js
- email_mailbox/src/components/ManualSyncProcessPopup.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/electronInterface.js
- email_mailbox/src/utils/ipc.js
Events:
- 303
- 304
- 306
- 307
Fixes:
- Next logged account on logging out
- Delete previous account data on Mailbox Sync
- Create login window bug
> Multiple Accounts: Fixes: Peer events & Link/Sync

- electron_app/src/DBManager.js
- electron_app/src/ipc/database.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- Hanlde `inReplyTo` when receiving new email
> In Reply To

- email_composer/package.json
- email_composer/src/containers/Composer.js
- email_composer/src/utils/ipc.js
- email_composer/yarn.lock
- email_mailbox/package.json
- email_mailbox/src/utils/FileManager.js
- email_mailbox/yarn.lock
- Handle 401 status code on file download/upload
> Refresh on file server when returning 401

- electron_app/src/dataTransferClient.js
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/components/LinkOldDeviceWrapper.js
- Catch error for Data Transfer
- Retry upload/download of db
> Catch Error and Retry Linking when DataTransfer fails

- electron_app/src/utils/const.js
- email_composer/src/containers/Composer.js
- email_composer/src/libs/signal.js
- email_composer/src/utils/EmailUtils.js
- email_composer/src/utils/EncryptionUtils.js
- email_composer/src/utils/__tests__/EncryptionUtils.js
- email_composer/src/utils/__tests__/__snapshots__/EmailUtils.js.snap
- email_mailbox/src/utils/electronEventInterface.js
- Update to find keybundle v9.0.0
- Update to post email v9.0.0
- Change request post data
- Handle blacklisted and new keybundles with enterprise recipientIds
- Create Criptext Emails with enterprise recipientIds
- Create Guest Emails with GuesDomains
> Find KeyBundle and Post Email v9.0.0

- electron_app/src/globalManager.js
- electron_app/src/socketClient.js
- electron_app/src/windows/composer.js
- electron_app/src/windows/mailbox.js
- email_composer/src/containers/Composer.js
- email_composer/src/utils/electronInterface.js
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/components/Loading.js
- email_loading/src/components/LoadingWrapper.js
- email_loading/src/lang/en.json
- email_loading/src/lang/es.json
- email_loading/src/utils/electronInterface.js
- email_mailbox/src/containers/Panel.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/electronInterface.js
Composer: 
- Stop getting events on sending message
Loading:
- Stop window closing until mailbox window is ready
> Getting Events Handling

- email_composer/src/containers/Composer.js
- email_mailbox/src/utils/EmailUtils.js
- email_mailbox/src/utils/electronEventInterface.js
- Fix when sending and receiving emails while using an enterprise account
> Receiving and Sending from Peers

- electron_app/src/clientManager.js
- electron_app/src/ipc/mailbox.js
- electron_app/src/ipc/utils.js
- electron_app/src/socketClient.js
- electron_app/src/windows/mailbox.js
- email_login/src/components/LoginWrapper.js
- email_mailbox/src/lang/es.json
Fixes:
- **Socket disconnect** (resolve)
- **Prefix warning**
> Multiple accounts: Fix socket disconnect

- electron_app/src/ipc/mailbox.js
- electron_app/src/ipc/manager.js
- electron_app/src/windows/mailbox.js
- email_mailbox/src/components/PanelWrapper.js
- email_mailbox/src/components/Thread.js
- email_mailbox/src/lang/es.json
- email_mailbox/src/libs/scopedStore.js
- email_mailbox/src/libs/signal.js
- email_mailbox/src/utils/FetchUtils.js
- email_mailbox/src/utils/FileManager.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- Receiving a new email push notification retrieve that single event and parses it
- Works with background accounts
> Handle one new email when receiving push notification

- electron_app/src/Account.js
- electron_app/src/DBManager.js
- electron_app/src/migrations/20190206105940_addColumnScore.js
- electron_app/src/migrations/20190529120002_addEncryptToExternals.js
- email_composer/src/containers/Composer.js
- email_mailbox/src/components/SettingAccount.js
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/components/settings.scss
- email_mailbox/src/containers/Email.js
- email_mailbox/src/containers/SettingsGeneralProfile.js
- email_mailbox/src/containers/ThreadItem.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/AccountUtils.js
- Migrate db to support `encryptToExternals`
- Add option in settings
- Toggle password popup based on the value of `encryptToExternals`
> Encrypt to Externals optional with password

- email_mailbox/src/components/EmailWrapper.js
- email_mailbox/src/utils/FileManager.js
Fixes:
- Missing error on downloading any file
- Download inline images on mounting component
> Fix inline images download

- electron_app/src/ipc/mailbox.js
- electron_app/src/utils/FileUtils.js
- email_composer/src/components/editor.scss
- email_mailbox/src/components/EmailWrapper.js
- email_mailbox/src/components/FileWrapper.js
- email_mailbox/src/components/UserGuide.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/FileManager.js
> Attachments Suffix  &  'Secure Email' User Guide Step

- electron_app/src/Account.js
- electron_app/src/DBManager.js
- electron_app/src/migrations/20190805181448_signFooter.js
- email_composer/src/lang/en.json
- email_composer/src/lang/es.json
- email_composer/src/utils/EmailUtils.js
- email_mailbox/src/components/SettingAccount.js
- email_mailbox/src/components/SettingBlockProfile.js
- email_mailbox/src/components/SettingBlockProfileWrapper.js
- email_mailbox/src/components/settingblockprofile.scss
- email_mailbox/src/containers/SettingBlockProfile.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
> Settings: Add criptext signature footer option to show or not

- electron_app/src/windows/composer.js
- email_mailbox/src/data/message.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/electronEventInterface.js
> Save Drafts automatically (no dialog)

- electron_app/src/migrations/20190816144157_addColumnsRecordLength.js
- electron_app/src/models.js
- email_mailbox/src/actions/app.js
- email_mailbox/src/components/MigrationPopupWrapper.js
- email_mailbox/src/components/Panel.js
- email_mailbox/src/components/PanelWrapper.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/utils/electronEventInterface.js
- signal_interface/linux_binding.gyp
- signal_interface/linux_install_deps.sh
- signal_interface/main.cpp
Steps
- Parse pending events before Alice migration (using `useLegacy` variable)
- Run migration to upgrade
- Check pending backups and run it
Fixes
- Update Alice migration timestamp
- Fix alice script
> Alice migration

- .gitignore
- db_interface/src/axolotl/Account.cpp
- db_interface/src/axolotl/Account.h
- db_interface/src/axolotl/IdentityKey.cpp
- db_interface/src/axolotl/IdentityKey.h
- db_interface/src/axolotl/PreKey.cpp
- db_interface/src/axolotl/PreKey.h
- db_interface/src/axolotl/SessionRecord.cpp
- db_interface/src/axolotl/SessionRecord.h
- db_interface/src/axolotl/SignedPreKey.cpp
- db_interface/src/axolotl/SignedPreKey.h
- electron_app/electron-starter.js
- signal_interface/CMakeLists.txt
- signal_interface/binding.gyp
- signal_interface/linux_binding.gyp
- signal_interface/main.cpp
- signal_interface/src/crypto/protocol_store/IdentityKeyStore.cpp
- signal_interface/src/crypto/protocol_store/PreKeyStore.cpp
- signal_interface/src/crypto/protocol_store/SessionStore.cpp
- signal_interface/src/crypto/protocol_store/SignedPreKeyStore.cpp
- signal_interface/src/crypto/signal.cpp
- signal_interface/src/http/handlers/decrypt.cpp
- signal_interface/src/http/handlers/encrypt.cpp
- signal_interface/src/http/handlers/helpers.cpp
- signal_interface/src/http/handlers/helpers.h
- signal_interface/src/http/handlers/keyBundle.cpp
- Alice properly works now on Linux
- Removing SqliteCPP dependencies
- Remove mallocs
> Alice Working in Linux

- electron_app/src/utils/RegexUtils.js
- electron_app/src/utils/__tests__/RegexUtils.js
- email_composer/src/utils/RegexUtils.js
- email_mailbox/src/utils/RegexUtils.js
- email_mailbox/src/utils/__tests__/EmailUtils.js
- email_mailbox/src/utils/__tests__/__snapshots__/EmailUtils.js.snap
> Accept external email addresses format

- electron_app/src/aliceManager.js
- email_composer/src/utils/ApiUtils.js
- email_composer/src/utils/electronInterface.js
- email_mailbox/src/libs/signal.js
- email_mailbox/src/utils/AESUtils.js
- email_mailbox/src/utils/ApiUtils.js
- email_mailbox/src/utils/electronInterface.js
- signal_interface/main.cpp
- signal_interface/src/crypto/crypto.c
- signal_interface/src/crypto/crypto.h
- signal_interface/src/crypto/protocol_store/SignedPreKeyStore.cpp
- signal_interface/src/http/handlers/decrypt.cpp
- signal_interface/src/http/handlers/decrypt.h
- signal_interface/src/http/handlers/encrypt.cpp
- signal_interface/src/http/handlers/encrypt.h
- signal_interface/src/http/http.cpp
- signal_interface/src/http/http.h
- Initializing Alice with a password
- Encrypting `post email` payload before sending it
- Encrypting `fetch decrypt` response before sending it
> AES Encrypting and Decrypting sensible data for transit

- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/ipc/client.js
- electron_app/yarn.lock
- email_login/src/app.scss
- email_login/src/components/DeviceNotApproved.js
- email_login/src/components/PanelWrapper.js
- email_login/src/components/RecoveryCodePopup.js
- email_login/src/components/RecoveryCodeWrapperPopup.js
- email_login/src/components/SignInToApprove.js
- email_login/src/lang/en.json
- email_login/src/lang/es.json
- email_login/src/utils/ipc.js
- email_mailbox/src/components/ManualSyncDeviceAuthenticationPopup.js
- email_mailbox/src/components/ManualSyncProcessPopup.js
- email_mailbox/src/utils/ipc.js
- Sending Link/Sync cancel when living link/sync screen.
- Generating and Validating recovery code in popup
> Link Cancel and 2FA Recovery Code

- email_mailbox/src/actions/threads.js
- email_mailbox/src/components/HeaderThreadOptionsWrapper.js
- email_mailbox/src/containers/HeaderThreadOptions.js
- email_mailbox/src/reducers/threads.js
- Does not remove thread if label being removed is not the one from current mailbox
> Keep thread if has current mailbox label

- email_login/src/components/DeleteDeviceWrapperPopup.js
- email_mailbox/src/components/ManualSyncProcessPopup.js
- email_mailbox/src/components/PanelWrapper.js
- email_mailbox/src/utils/electronEventInterface.js
refresh mailbox after sync and back button enabled on remove devices in login
> Mailbox Sync  Refresh

- electron_app/src/notificationManager.js
- electron_app/src/utils/PrintUtils.js
- Persisting notifications to prevent on click function to fail
> Notifications properly open thread

- email_pin/src/components/EnterPin.js
- signal_interface/binding.template.gyp
- signal_interface/installation/macos/macos_binding.gyp
- signal_interface/installation/macos/macos_install_deps.sh
Alice is able to compile using SQLCipher with the added modifications
> Sqlcipher working on MacOS

- electron_app/src/filescript/checker.js
- electron_app/src/filescript/decrypter.js
- electron_app/src/filescript/handler.js
- electron_app/src/filescript/helpers.js
- Methods to encrypt and decrypt files as stream with AES
- Script to encrypt existing email bodies and headers
> Script to encrypt existing email bodies and headers 

- electron_app/src/clientManager.js
- electron_app/src/ipc/client.js
- email_mailbox/src/actions/emails.js
- email_mailbox/src/components/Email.js
- email_mailbox/src/components/EmailActions.js
- email_mailbox/src/containers/Email.js
- email_mailbox/src/containers/HeaderThreadOptions.js
- email_mailbox/src/data/message.js
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/selectors/threads.js
- email_mailbox/src/utils/ipc.js
- When moving threads to SPAM, senders are reported as spam
- When moving an email to SPAM, the sender is reported as spam
- Now you can report an email as Phishing
> Spam and Phishing Report

- electron_app/electron-starter.js
- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/utils/const.js
- electron_app/src/windows/composer.js
- electron_app/yarn.lock
- email_composer/package.json
- email_loading/package.json
- email_login/package.json
- email_mailbox/package.json
- Added tracking events for composer open and app open
> Added Tracking Events

- electron_app/package.json
- email_composer/package.json
- email_loading/package.json
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/libs/signal.js
- email_login/package.json
- email_mailbox/package.json
- Fixing a bug where trying to log in with your full criptext email address link device gets stuck at 70%
> Unable to Link device in login

- electron_app/electron-starter.js
- electron_app/src/aliceManager.js
- signal_interface/src/crypto/signal.cpp
- Don't close App if Alice has successfully started at start of app
- Interrupt decrypt message if message is not parsed by signal
> Don't close App if Alice can run

- email_mailbox/src/components/Thread.js
Fix over last email of thread is not shown after delete.
> fix over last email of threas is deleted

- electron_app/src/database/DBEexporter.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/utils/FileUtils.js
- electron_app/src/utils/dataBaseUtils.js
- electron_app/src/windows/pin.js
- Loading bodies and haders from filesystem when exporting data from unencrypted db
- Creating a copy of emails being imported until process is complete
> Fix export of data from unencrypted db

- email_login/src/components/DeleteDeviceWrapperPopup.js
- email_login/src/components/deletedevicepopup.scss
- email_mailbox/src/components/PasswordChangedPopup.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- fix: popup when a peer device changes the password was not localized
- fix: Delete button in the devices limit reached screen should start disabled
> some UI fixes

- db_interface/src/dbUtils.cpp
- Added a flag to enable encryption service to handle multiple accesses to encrypted db
> Encrypting emails in parallel

- .gitignore
- db_interface/src/axolotl/Account.cpp
- db_interface/src/axolotl/Account.h
- db_interface/src/axolotl/IdentityKey.cpp
- db_interface/src/axolotl/IdentityKey.h
- db_interface/src/axolotl/PreKey.cpp
- db_interface/src/axolotl/PreKey.h
- db_interface/src/axolotl/SessionRecord.cpp
- db_interface/src/axolotl/SessionRecord.h
- db_interface/src/axolotl/SignedPreKey.cpp
- db_interface/src/axolotl/SignedPreKey.h
- db_interface/src/dbUtils.cpp
- signal_interface/src/crypto/protocol_store/IdentityKeyStore.cpp
- signal_interface/src/crypto/protocol_store/PreKeyStore.cpp
- signal_interface/src/crypto/protocol_store/SessionStore.cpp
- signal_interface/src/crypto/protocol_store/SignedPreKeyStore.cpp
- signal_interface/src/crypto/signal.cpp
- signal_interface/src/crypto/signal.h
- signal_interface/src/http/handlers/decrypt.cpp
- signal_interface/src/http/handlers/decrypt.h
- signal_interface/src/http/handlers/encrypt.cpp
- signal_interface/src/http/handlers/keyBundle.cpp
- signal_interface/src/http/handlers/keyBundle.h
- Use one SQLite connection for the whole request, improving speed when doing subsequent queries
- Enable WAL mode to ensure Reading and Writing concurrency
> Alice Performance Improvements

- email_mailbox/src/components/Thread.js
- email_mailbox/src/containers/HeaderThreadOptions.js
- email_mailbox/src/containers/Thread.js
- email_mailbox/src/utils/ContactUtils.js
Send not spam to report contact at no spam.
> add notspam to report contact when emails are not spam

- electron_app/src/eventQueueManager.js
- email_mailbox/src/containers/Email.js
- email_mailbox/src/utils/electronEventInterface.js
- When returning from a reply, thread info does not update properly
- Pending events are not dispatched regularly
> some fixes

- .gitignore
- electron_app/package.json
- electron_app/src/database/DBEmodel.js
- electron_app/src/database/migrations/20200123161254-multipleAccounts.js
- electron_app/yarn.lock
- Migrating DB adding `accountId` column to needed tables
- Using `umzug` to handle migrations
> migration up, creating account id

- signal_interface/src/crypto/signal.cpp
- signal_interface/src/crypto/signal.h
- signal_interface/src/http/handlers/cors.cpp
- signal_interface/src/http/handlers/cors.h
- signal_interface/src/http/handlers/decrypt.cpp
- signal_interface/src/http/handlers/encrypt.cpp
- signal_interface/src/http/handlers/helpers.cpp
- signal_interface/src/http/handlers/helpers.h
- signal_interface/src/http/handlers/keyBundle.cpp
- Encryption service now correctly returns http error codes
- Signal erros are described in encryption service's log file
> Correctly returning errors from encryption service

- electron_app/src/aliceManager.js
- electron_app/src/filescript/helpers.js
- signal_interface/main.cpp
- signal_interface/src/crypto/protocol_store/SessionStore.cpp
- signal_interface/src/crypto/protocol_store/SignedPreKeyStore.cpp
- signal_interface/src/http/handlers/decrypt.cpp
- signal_interface/src/http/handlers/encrypt.cpp
- signal_interface/src/http/handlers/keyBundle.cpp
- signal_interface/src/http/handlers/password.cpp
- signal_interface/src/http/handlers/password.h
- signal_interface/src/http/http.cpp
- signal_interface/src/http/http.h
- Encryption Service generates a token and passes it to Electron
- Electron encrypts the pin with that token and sends it to the Encryption Service
- Encryption Service decrypts the pin and updates it
> passing pin encrypted to start alice

- electron_app/src/__integrations__/DbExporter.integration.js
- electron_app/src/database/DBEexporter.js
> Fixed some test from DBEexport

- electron_app/src/Settings.js
- electron_app/src/__integrations__/DbExporter.integration.js
- electron_app/src/__integrations__/parsed_sample_file.txt
- electron_app/src/database/DBEexporter.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/backup.js
- electron_app/src/ipc/database.js
- email_mailbox/src/components/Settings.js
- email_mailbox/src/components/SettingsAccountBackup.js
- email_mailbox/src/components/SettingsAccountBackupWrapper.js
- email_mailbox/src/components/SettingsWrapper.js
- email_mailbox/src/containers/HeaderMain.js
- Backup works and updates new Account columns
- Creates label for account
> Settings update

- db_interface/src/axolotl/IdentityKey.cpp
- db_interface/src/axolotl/PreKey.cpp
- db_interface/src/axolotl/SessionRecord.cpp
- db_interface/src/axolotl/SignedPreKey.cpp
- electron_app/src/dataTransferClient.js
- electron_app/src/database/DBEexporter.js
- electron_app/src/database/DBEmigrations/20200123161254-multipleAccounts.js
- electron_app/src/database/DBEmodel.js
- electron_app/src/ipc/mailbox.js
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/components/LoadingWrapper.js
- email_loading/src/libs/signal.js
- email_loading/src/utils/ipc.js
- email_mailbox/src/utils/electronEventInterface.js
- signal_interface/src/crypto/protocol_store/SignedPreKeyStore.cpp
Adding account through:
- Sign Up
- Sign In with password
- Sign In Link Device
> Add New Account

- electron_app/src/__integrations__/Email.integration.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/manager.js
- email_mailbox/src/containers/ActivityPanel.js
Corrected bug of delete permanent bug crash the app.
> Delete permanent bug2

- electron_app/src/database/DBEmanager.js
- electron_app/src/database/DBEmigrations/20200123161254-multipleAccounts.js
- electron_app/src/database/DBEmodel.js
- electron_app/src/ipc/manager.js
- email_loading/src/libs/signal.js
- email_mailbox/src/components/DeleteAccountPopupWrapper.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- DB Migration:
- Add Unique Index to `contact.email`
- Drop email and recreate table with `email.key` as not unique
- Recreate registries of emailId
- Delete Account deletes rows only related to account being deleted
> Migration And Delete Account

- email_mailbox/src/utils/electronEventInterface.js
refactor handleNewMessageEvent in electron event interface
> refactor handleNewMessageEvent in electron event interface

- electron_app/src/BackupManager.js
- electron_app/src/dataTransferClient.js
- electron_app/src/database/DBEexporter.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/backup.js
- electron_app/src/windows/login.js
- email_loading/src/libs/signal.js
- email_mailbox/src/components/SettingsAccountBackupWrapper.js
- email_mailbox/src/utils/ipc.js
- Autobackup starts timers for every account
- Fixed inserting multiple contacts already in DB
> Auto Backup for Multiple Accounts

- electron_app/src/database/DBEmanager.js
- electron_app/src/filescript/handler.js
- electron_app/src/ipc/database.js
- electron_app/src/ipc/mailbox.js
- electron_app/src/ipc/manager.js
- electron_app/src/rekeyHandler.js
- electron_app/src/utils/SourceUtils.js
- email_loading/src/libs/signal.js
- email_loading/src/utils/ipc.js
- email_mailbox/src/actions/emails.js
- email_mailbox/src/actions/labels.js
- email_mailbox/src/actions/threads.js
- email_mailbox/src/utils/EmailUtils.js
- email_mailbox/src/utils/__tests__/EmailUtils.js
- email_mailbox/src/utils/electronEventInterface.js
- email_pin/src/components/VCSignupWrapper.js
- Delete Emails Permanently
- Parsing Event
- Show Source
> Fixing Bugs

- electron_app/src/database/DBEmanager.js
- electron_app/src/database/DBEmodel.js
- electron_app/src/windows/index.js
- electron_app/src/windows/launch.js
- electron_app/src/windows/pin.js
- electron_app/src/windows/preparing.html
- electron_app/src/windows/source-light.html
- On App Start, shows a migration popup if necessary
> Launch Window

- email_mailbox/src/components/Panel.js
- email_mailbox/src/components/PanelWrapper.js
- email_mailbox/src/components/UpdatePopup.js
- email_mailbox/src/components/updatepopup.scss
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- email_mailbox/src/utils/electronEventInterface.js
> update for popup when receiving large image

- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/eventQueueManager.js
- electron_app/src/ipc/client.js
- electron_app/src/ipc/mailbox.js
- electron_app/src/ipc/utils.js
- electron_app/src/reachabilityTask.js
- electron_app/src/windows/index.js
- email_composer/package.json
- email_composer/src/libs/signal.js
- email_composer/src/utils/ipc.js
- email_loading/package.json
- email_loading/src/components/LinkNewDeviceWrapper.js
- email_loading/src/libs/signal.js
- email_loading/src/utils/electronEventInterface.js
- email_loading/src/utils/ipc.js
- email_login/package.json
- email_login/src/components/PanelWrapper.js
- email_login/src/components/SignUpWrapper.js
- email_login/src/utils/ipc.js
- email_mailbox/package.json
- email_mailbox/src/components/DeleteAccountPopupWrapper.js
- email_mailbox/src/components/ManualSyncProcessPopup.js
- email_mailbox/src/selectors/labels.js
- email_mailbox/src/utils/FetchUtils.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- email_pin/package.json
> refactor in clientManager, fetchUtils and bug fixes

- electron_app/src/clientManager.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/client.js
- email_mailbox/src/components/CustomDomains.js
- email_mailbox/src/components/CustomDomainsWrapper.js
- email_mailbox/src/components/DeleteCustomDomainPopup.js
- email_mailbox/src/components/MxLoadingWrapper.js
- email_mailbox/src/components/SettingAccount.js
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/components/SettingCustomDomainsBlock.js
- email_mailbox/src/components/SettingsContainer.js
- email_mailbox/src/components/SettingsPopup.js
- email_mailbox/src/components/settingcustomdomainsblock.scss
- email_mailbox/src/data/message.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
> Delete custom domain

- electron_app/src/clientManager.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/database/DBEmodel.js
- electron_app/src/ipc/client.js
- electron_app/src/ipc/database.js
- email_mailbox/src/components/AliasesWrapper.js
- email_mailbox/src/components/CustomDomains.js
- email_mailbox/src/components/CustomDomainsWrapper.js
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/components/SettingsContainer.js
- email_mailbox/src/components/customDomains.scss
- email_mailbox/src/containers/SettingsContainer.js
- email_mailbox/src/utils/ipc.js
Some improvements over custom domains and aliases
> improvements over custom domains and addresses 1

- email_composer/src/containers/Composer.js
- email_composer/src/libs/signal.js
- email_mailbox/src/components/DeleteAliasPopup.js
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- signal_interface/src/crypto/protocol_store/PreKeyStore.cpp
- signal_interface/src/crypto/protocol_store/SessionStore.cpp
- Added `aliasUsername` and `aliasDomain` when sending an email to an alias
- Delete alias handles event `428`, shows remaining days to delete
> Sent to Alias and Delete Alias 

- README.md
- db_interface/linux_setup.sh
- signal_interface/installation/linux/linux_install_deps.sh
I modified db_interface/linux_setup.sh and signal_interface/installation/linux/linux_install_deps.sh to build Alice in an Arch Linux system.
I hope it can be useful.
Meph
> Build Alice on Arch Linux

- db_interface/linux_setup.sh
- install.js
- signal_interface/installation/linux/linux_binding.gyp
- signal_interface/installation/linux/linux_install_deps.sh
Change some issues in installation on Linux
> add some changes in installation on linux files

- email_mailbox/src/components/AvatarImage.js
- email_mailbox/src/components/SettingsPopup.js
- email_mailbox/src/components/UpgradeToPlusPopup.js
> updating avatar image border

- email_composer/src/containers/Composer.js
- email_mailbox/src/components/MainErrorBoundary.js
- email_mailbox/src/containers/HeaderMain.js
- email_mailbox/src/containers/Thread.js
- email_mailbox/src/selectors/threads.js
- Fixed a bug when searching emails twice and clicking any suggestion was crashing the app
> Search Emails Suggestions

- electron_app/src/database/DBEmanager.js
- email_mailbox/src/actions/threads.js
- email_mailbox/src/components/SettingAccount.js
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/components/emailblocked.scss
- email_mailbox/src/containers/HeaderThreadOptions.js
- email_mailbox/src/containers/Thread.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
Bugs:
- infinite loading in settings
- some issues with localization
- if change of label move is trusted or not depending on situation
> solve some bugs including not istrusted if change from spam to mailbox

- email_mailbox/src/components/UpdatePopup.js
- email_mailbox/src/components/updatepopup.scss
- email_mailbox/src/utils/electronEventInterface.js
- Checking version by operator to show news update
- Hiding buttons if update is not needed
> Update Popup by Version

- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/logger.js
- email_mailbox/src/components/AliasesWrapper.js
- email_mailbox/src/components/CustomDomains.js
- email_mailbox/src/components/CustomDomainsWrapper.js
- email_mailbox/src/containers/SettingsContainer.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- email_mailbox/src/utils/RegexUtils.js
- email_mailbox/src/utils/ipc.js
- Adding domain validations
- Parsing Addresses in Settings
- Logging parsing errors
> Domain and Addresses fix

- electron_app/package.json
- email_composer/package.json
- email_loading/package.json
- email_login/package.json
- email_mailbox/package.json
- email_pin/package.json
> updated version 0.29.3

- electron_app/src/clientManager.js
- email_login/src/components/PanelWrapper.js
- email_mailbox/src/data/message.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- email_mailbox/src/utils/electronEventInterface.js
Also now properly creates database if logged with 2fa and recovery code
> not removing device if auth fails, only if removed device

- electron_app/package.json
- electron_app/src/clientManager.js
- electron_app/src/ipc/client.js
- electron_app/yarn.lock
- email_mailbox/src/components/SettingAccountWrapper.js
- email_mailbox/src/components/SettingsPopup.js
- email_mailbox/src/libs/signal.js
- email_mailbox/src/utils/electronEventInterface.js
- email_mailbox/src/utils/ipc.js
- Also recovery email popup with password fix
> Reencrypting Email

- electron_app/package.json
- email_composer/package.json
- email_loading/package.json
- email_login/package.json
- email_mailbox/package.json
- email_pin/package.json
>  0.30.0 desktop

- electron_app/src/BackupManager.js
- electron_app/src/backup/Compress.js
- electron_app/src/backup/DBEexporter.js
- electron_app/src/backup/FileUtils.js
- electron_app/src/backup/databaseExport.js
- electron_app/src/backup/exporter.js
- electron_app/src/backup/index.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/database/DBEmodel.js
- electron_app/src/ipc/backup.js
- electron_app/src/utils/FileUtils.js
- email_login/src/validators/validators.js
- email_mailbox/src/components/SettingsAccountBackupWrapper.js
- Backup Child Process avoids main thread lag
- Fix next backup timeout if number overflows maximum time
> Backup worker

- electron_app/electron-starter.js
- electron_app/src/database/DBEmodel.js
- email_mailbox/src/utils/electronEventInterface.js
- Report Spam
- Show error dialog on migration fail and if app throws exception
> Report spam

- electron_app/electron-starter.js
- electron_app/src/Account.js
- electron_app/src/__mocks__/Account.js
- electron_app/src/backup/databaseExport.js
- electron_app/src/backup/index.js
- electron_app/src/database/DBEmanager.js
- electron_app/src/ipc/composer.js
- electron_app/src/lang/de.json
- electron_app/src/lang/en.json
- electron_app/src/lang/es.json
- electron_app/src/lang/fr.json
- electron_app/src/lang/ru.json
- electron_app/src/utils/dataTableUtils.js
- electron_app/src/windows/composer.js
- electron_app/src/windows/menu.js
- email_mailbox/src/components/PasswordChangedPopup.js
- email_mailbox/src/components/PasswordChangedPopupWrapper.js
- email_mailbox/src/components/RemoveDevicePopupWrapper.js
- email_mailbox/src/components/SettingDevicesWrapper.js
- email_mailbox/src/components/SettingsContainer.js
- email_mailbox/src/components/ThreadsWrapper.js
- email_mailbox/src/containers/SettingsContainer.js
- email_mailbox/src/lang/de.json
- email_mailbox/src/lang/en.json
- email_mailbox/src/lang/es.json
- email_mailbox/src/lang/fr.json
- email_mailbox/src/lang/ru.json
- email_mailbox/src/utils/electronEventInterface.js
- Remove Device displaying error
- Overwriting my own contact with my name
- Saving Email if Composer goes on background
- Load more emails when threads number changes but is not big enough to trigger scroll
- Adding loader to `password changed` popup
> Multiple Fixes
